name: OCI Provisioning

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: Preparar Chave Privada
        run: |
          # Cria um .env vazio só para o script PHP não dar erro de arquivo não encontrado
          touch .env
          
          # Cria o arquivo da chave privada isolado e seguro
          echo "${{ secrets.OCI_KEY_FILE }}" > oci_api_key.pem
          chmod 600 oci_api_key.pem

      - name: Run provisioning
        env:
          # Injeção direta no sistema, sem risco de quebrar por causa de espaços!
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          OCI_OCPUS: 4
          OCI_MEMORY_IN_GBS: 24
          OCI_SHAPE: VM.Standard.A1.Flex
          OCI_PRIVATE_KEY_FILENAME: oci_api_key.pem
        run: php index.php
